#!/usr/bin/python3



def raiise_exception_msg(message=""):
    raise NameError(message)
